import i18n from '@/lang'

export const iconTypeList = () => [
  // { value: '0', label: '常用' },
  { value: '1', label: i18n.t('customIconSelect.outlined') },
  { value: '2', label: i18n.t('customIconSelect.filled') },
  { value: '3', label: i18n.t('customIconSelect.multicolor') }
]

export const commonIconList = ['changyong-ubuntu',
  'changyong-centos',
  'changyong-changyonglogo45',
  'changyong-pingguo',
  'changyong-windows',
  'changyong-Oracle',
  'changyong-freebsd',
  'changyong-mysql',
  'changyong-fedora',
  'changyong-linux',
  'changyong-sqlite',
  'changyong-memcached',
  'changyong-pingtaiyunweiguanli',
  'changyong-debian',
  'changyong-googlecloud',
  'changyong-mongodb',
  'changyong-redhat',
  'changyong-redis',
  'changyong-amazon',
  'changyong-alibabacloud',
  'changyong-SQLServer',
  'changyong-Sybase',
  'changyong-PostgreSQL',
  'changyong-SUSE',
  'changyong-huawei',
  'changyong-weiruan',
  'changyong-ziyuan40',
  'changyong-tengxunyun',
  'changyong-php',
  'changyong-visual-studio',
  'changyong-java',
  'changyong-ruby',
  'changyong-powershell',
  'changyong-C',
  'changyong-cyuyan',
  'changyong-Python']

export const linearIconList = [
  {
    value: 'database',
    label: 'components.database',
    list: [{
      value: 'icon-xianxing-DB2',
      label: 'DB2'
    }, {
      value: 'icon-xianxing-oracle',
      label: 'Oracle'
    }, {
      value: 'icon-xianxing-informix',
      label: 'Informix'
    }, {
      value: 'icon-xianxing-Sybase',
      label: 'Sybase'
    }, {
      value: 'icon-xianxing-SQLServer',
      label: 'SQLServer'
    }, {
      value: 'icon-xianxing-PostgreSQL',
      label: 'PostgreSQL'
    }, {
      value: 'icon-xianxing-mySQL',
      label: 'mySQL'
    }, {
      value: 'icon-xianxing-access',
      label: 'access'
    }, {
      value: 'icon-xianxing-mongodb',
      label: 'mongodb'
    }, {
      value: 'icon-xianxing-redis',
      label: 'redis'
    }]
  }, {
    value: 'system',
    label: 'components.system',
    list: [{
      value: 'icon-xianxing-Windows',
      label: 'Windows'
    }, {
      value: 'icon-xianxing-Linux',
      label: 'Linux'
    }, {
      value: 'icon-xianxing-unix',
      label: 'Unix'
    }, {
      value: 'icon-xianxing-Mac',
      label: 'Mac'
    }, {
      value: 'icon-xianxing-Ubuntu',
      label: 'Ubuntu'
    }, {
      value: 'icon-xianxing-centos',
      label: 'Centos'
    }, {
      value: 'icon-xianxing-redhat',
      label: 'Redhat'
    }]
  }, {
    value: 'language',
    label: 'components.language',
    list: [{
      value: 'icon-xianxing-python',
      label: 'python'
    }, {
      value: 'icon-xianxing-Java',
      label: 'Java'
    }, {
      value: 'icon-xianxing-c1',
      label: 'C++'
    }, {
      value: 'icon-xianxing-c2',
      label: 'C#'
    }, {
      value: 'icon-xianxing-swift',
      label: 'Swift'
    }, {
      value: 'icon-xianxing-php',
      label: 'PHP'
    }, {
      value: 'icon-xianxing-shell',
      label: 'Shell'
    }, {
      value: 'icon-xianxing-powershell',
      label: 'PowerShell'
    }, {
      value: 'icon-xianxing-bat',
      label: 'Bat'
    }]
  }, {
    value: 'status',
    label: 'components.status',
    list: [{
      value: 'icon-xianxing-yiwen',
      label: i18n.t('iconLabels.question')
    }, {
      value: 'icon-xianxing-zanting',
      label: i18n.t('iconLabels.pause')
    }, {
      value: 'icon-xianxing-tianjia',
      label: i18n.t('iconLabels.add')
    }, {
      value: 'icon-xianxing-jianqu',
      label: i18n.t('iconLabels.subtract')
    }, {
      value: 'icon-xianxing-quxiao',
      label: i18n.t('iconLabels.cancel')
    }, {
      value: 'icon-xianxing-queren',
      label: i18n.t('iconLabels.confirm')
    }, {
      value: 'icon-xianxing-jinggao',
      label: i18n.t('iconLabels.warning')
    }, {
      value: 'icon-xianxing-jinzhi',
      label: i18n.t('iconLabels.forbidden')
    }, {
      value: 'icon-xianxing-shuoming',
      label: i18n.t('iconLabels.description')
    }, {
      value: 'icon-xianxing-chulizhong',
      label: i18n.t('iconLabels.processing')
    }, {
      value: 'icon-xianxing-zaixian',
      label: i18n.t('iconLabels.online')
    }, {
      value: 'icon-xianxing-xiaxian',
      label: i18n.t('iconLabels.offline')
    }]
  }, {
    value: 'icon-xianxing-application',
    label: 'components.commonComponent',
    list: [{
      value: 'icon-xianxing-yilianjie',
      label: i18n.t('iconLabels.connected')
    }, {
      value: 'icon-xianxing-weilianjie',
      label: i18n.t('iconLabels.disconnected')
    }, {
      value: 'icon-xianxing-shoucang',
      label: i18n.t('iconLabels.favorites')
    }, {
      value: 'icon-xianxing-baojing',
      label: i18n.t('iconLabels.alarm')
    }, {
      value: 'icon-xianxing-erweima',
      label: i18n.t('iconLabels.qrCode')
    }, {
      value: 'icon-xianxing-fenzhi',
      label: i18n.t('iconLabels.branch')
    }, {
      value: 'icon-xianxing-yunshuju',
      label: i18n.t('iconLabels.cloudData')
    }, {
      value: 'icon-xianxing-yunshangchuan',
      label: i18n.t('iconLabels.cloudUpload')
    }, {
      value: 'icon-xianxing-yunxiazai',
      label: i18n.t('iconLabels.cloudDownload')
    }, {
      value: 'icon-xianxing-xiaoxi',
      label: i18n.t('iconLabels.message')
    }, {
      value: 'icon-xianxing-dingwei',
      label: i18n.t('iconLabels.location')
    }, {
      value: 'icon-xianxing-guankan',
      label: i18n.t('iconLabels.view')
    }, {
      value: 'icon-xianxing-jinzhiguankan',
      label: i18n.t('iconLabels.noViewing')
    }, {
      value: 'icon-xianxing-yirenzheng',
      label: i18n.t('iconLabels.verified')
    }, {
      value: 'icon-xianxing-weirenzheng',
      label: i18n.t('iconLabels.unverified')
    }, {
      value: 'icon-xianxing-biaoqian',
      label: i18n.t('iconLabels.tag')
    }, {
      value: 'icon-xianxing-yonghu',
      label: i18n.t('iconLabels.user')
    }, {
      value: 'icon-xianxing-tianjiayonghu',
      label: i18n.t('iconLabels.addUser')
    }, {
      value: 'icon-xianxing-shanchuyonghu',
      label: i18n.t('iconLabels.deleteUser')
    }, {
      value: 'icon-xianxing-qiehuanyonghu',
      label: i18n.t('iconLabels.switchUser')
    }, {
      value: 'icon-xianxing-weixiu',
      label: i18n.t('iconLabels.maintenance')
    }, {
      value: 'icon-xianxing-wuliji',
      label: i18n.t('iconLabels.physicalMachine')
    }, {
      value: 'icon-xianxing-xuniji',
      label: i18n.t('iconLabels.virtualMachine')
    }, {
      value: 'icon-xianxing-docker',
      label: 'docker'
    }, {
      value: 'icon-xianxing-luyouqi',
      label: i18n.t('iconLabels.router')
    }, {
      value: 'icon-xianxing-jiaohuanji',
      label: i18n.t('iconLabels.switch')
    }, {
      value: 'icon-xianxing-fanghuoqiang',
      label: i18n.t('iconLabels.firewall')
    }, {
      value: 'icon-xianxing-fuzaijunheng',
      label: i18n.t('iconLabels.loadBalancer')
    }, {
      value: 'icon-xianxing-wangka',
      label: i18n.t('iconLabels.nic')
    }, {
      value: 'icon-xianxing-neicun',
      label: i18n.t('iconLabels.memory')
    }, {
      value: 'icon-xianxing-yingpan',
      label: i18n.t('iconLabels.hardDisk')
    }, {
      value: 'icon-xianxing-bumen',
      label: i18n.t('iconLabels.department')
    }, {
      value: 'icon-xianxing-chanpin',
      label: i18n.t('iconLabels.product')
    }, {
      value: 'icon-xianxing-dayinji',
      label: i18n.t('iconLabels.printer')
    }, {
      value: 'icon-xianxing-chajian',
      label: i18n.t('iconLabels.plugin')
    }, {
      value: 'icon-xianxing-yingyong',
      label: i18n.t('iconLabels.application')
    }, {
      value: 'icon-xianxing-nginx',
      label: 'Nginx'
    }, {
      value: 'icon-xianxing-apache',
      label: 'Apache'
    }, {
      value: 'icon-xianxing-tomcat',
      label: 'Tomcat'
    }, {
      value: 'icon-xianxing-aliyun',
      label: i18n.t('iconLabels.alibabaCloud')
    }, {
      value: 'icon-xianxing-tengxunyun',
      label: i18n.t('iconLabels.tencentCloud')
    }, {
      value: 'icon-xianxing-huaweiyun',
      label: i18n.t('iconLabels.huaweiCloud')
    }, {
      value: 'icon-xianxing-aws',
      label: 'AWS'
    }]
  }, {
    value: 'data',
    label: 'components.data',
    list: [{
      value: 'icon-xianxing-bingzhuangtu',
      label: i18n.t('iconLabels.pieChart')
    }, {
      value: 'icon-xianxing-huanxingtu',
      label: i18n.t('iconLabels.ringChart')
    }, {
      value: 'icon-xianxing-zhuzhuangtu',
      label: i18n.t('iconLabels.barChart')
    }, {
      value: 'icon-xianxing-tiaoxingtu',
      label: i18n.t('iconLabels.horizontalBar')
    }, {
      value: 'icon-xianxing-mianjitu',
      label: i18n.t('iconLabels.areaChart')
    }, {
      value: 'icon-xianxing-pubutu',
      label: i18n.t('iconLabels.waterfallChart')
    }, {
      value: 'icon-xianxing-xiangxingtu',
      label: i18n.t('iconLabels.boxPlot')
    }, {
      value: 'icon-xianxing-zhexiantu',
      label: i18n.t('iconLabels.lineChart')
    }, {
      value: 'icon-xianxing-dianzhuangtu',
      label: i18n.t('iconLabels.scatterPlot')
    }, {
      value: 'icon-xianxing-redutu',
      label: i18n.t('iconLabels.heatMap')
    }, {
      value: 'icon-xianxing-shangsheng',
      label: i18n.t('iconLabels.rising')
    }, {
      value: 'icon-xianxing-xiajiang',
      label: i18n.t('iconLabels.falling')
    }, {
      value: 'icon-xianxing-gupiaotu',
      label: i18n.t('iconLabels.stockChart')
    }, {
      value: 'icon-xianxing-jijintu',
      label: i18n.t('iconLabels.fundChart')
    }, {
      value: 'icon-xianxing-huakuaitu',
      label: i18n.t('iconLabels.sliderChart')
    }, {
      value: 'icon-xianxing-leidatu',
      label: i18n.t('iconLabels.radarChart')
    }, {
      value: 'icon-xianxing-shishu',
      label: i18n.t('iconLabels.integer')
    }, {
      value: 'icon-xianxing-fudianshu',
      label: i18n.t('iconLabels.float')
    }, {
      value: 'icon-xianxing-wenben',
      label: i18n.t('iconLabels.text')
    }, {
      value: 'icon-xianxing-datetime',
      label: 'datetime'
    }, {
      value: 'icon-xianxing-date',
      label: 'date'
    }, {
      value: 'icon-xianxing-time',
      label: 'time'
    }, {
      value: 'icon-xianxing-json',
      label: 'json'
    }]
  }
]

export const fillIconList = [
  {
    value: 'database',
    label: 'components.database',
    list: [{
      value: 'icon-shidi-DB2',
      label: 'DB2'
    }, {
      value: 'icon-shidi-oracle',
      label: 'Oracle'
    }, {
      value: 'icon-shidi-informix',
      label: 'Informix'
    }, {
      value: 'icon-shidi-Sybase',
      label: 'Sybase'
    }, {
      value: 'icon-shidi-SQLServer',
      label: 'SQLServer'
    }, {
      value: 'icon-shidi-PostgreSQL',
      label: 'PostgreSQL'
    }, {
      value: 'icon-shidi-mySQL',
      label: 'mySQL'
    }, {
      value: 'icon-shidi-access',
      label: 'access'
    }, {
      value: 'icon-shidi-mongodb',
      label: 'mongodb'
    }, {
      value: 'icon-shidi-redis',
      label: 'redis'
    }]
  }, {
    value: 'system',
    label: 'components.system',
    list: [{
      value: 'icon-shidi-Windows',
      label: 'Windows'
    }, {
      value: 'icon-shidi-Linux',
      label: 'Linux'
    }, {
      value: 'icon-shidi-unix',
      label: 'Unix'
    }, {
      value: 'icon-shidi-Mac',
      label: 'Mac'
    }, {
      value: 'icon-shidi-Ubuntu',
      label: 'Ubuntu'
    }, {
      value: 'icon-shidi-centos',
      label: 'Centos'
    }, {
      value: 'icon-shidi-redhat',
      label: 'Redhat'
    }]
  }, {
    value: 'language',
    label: 'components.language',
    list: [{
      value: 'icon-shidi-python',
      label: 'python'
    }, {
      value: 'icon-shidi-Java',
      label: 'Java'
    }, {
      value: 'icon-shidi-c1',
      label: 'C++'
    }, {
      value: 'icon-shidi-c2',
      label: 'C#'
    }, {
      value: 'icon-shidi-swift',
      label: 'Swift'
    }, {
      value: 'icon-shidi-php',
      label: 'PHP'
    }, {
      value: 'icon-shidi-shell',
      label: 'Shell'
    }, {
      value: 'icon-shidi-powershell',
      label: 'PowerShell'
    }, {
      value: 'icon-shidi-bat',
      label: 'Bat'
    }]
  }, {
    value: 'status',
    label: 'components.status',
    list: [{
      value: 'icon-shidi-yiwen',
      label: i18n.t('iconLabels.question')
    }, {
      value: 'icon-shidi-zanting',
      label: i18n.t('iconLabels.pause')
    }, {
      value: 'icon-shidi-tianjia',
      label: i18n.t('iconLabels.add')
    }, {
      value: 'icon-shidi-jianqu',
      label: i18n.t('iconLabels.subtract')
    }, {
      value: 'icon-shidi-quxiao',
      label: i18n.t('iconLabels.cancel')
    }, {
      value: 'icon-shidi-queren',
      label: i18n.t('iconLabels.confirm')
    }, {
      value: 'icon-shidi-jinggao',
      label: i18n.t('iconLabels.warning')
    }, {
      value: 'icon-shidi-jinzhi',
      label: i18n.t('iconLabels.forbidden')
    }, {
      value: 'icon-shidi-shuoming',
      label: i18n.t('iconLabels.description')
    }, {
      value: 'icon-shidi-chulizhong',
      label: i18n.t('iconLabels.processing')
    }, {
      value: 'icon-shidi-zaixian',
      label: i18n.t('iconLabels.online')
    }, {
      value: 'icon-shidi-xiaxian',
      label: i18n.t('iconLabels.offline')
    }]
  }, {
    value: 'icon-shidi-application',
    label: 'components.commonComponent',
    list: [{
      value: 'icon-shidi-yilianjie',
      label: i18n.t('iconLabels.connected')
    }, {
      value: 'icon-shidi-weilianjie',
      label: i18n.t('iconLabels.disconnected')
    }, {
      value: 'icon-shidi-shoucang',
      label: i18n.t('iconLabels.favorites')
    }, {
      value: 'icon-shidi-baojing',
      label: i18n.t('iconLabels.alarm')
    }, {
      value: 'icon-shidi-erweima',
      label: i18n.t('iconLabels.qrCode')
    }, {
      value: 'icon-shidi-fenzhi',
      label: i18n.t('iconLabels.branch')
    }, {
      value: 'icon-shidi-yunshuju',
      label: i18n.t('iconLabels.cloudData')
    }, {
      value: 'icon-shidi-yunshangchuan',
      label: i18n.t('iconLabels.cloudUpload')
    }, {
      value: 'icon-shidi-yunxiazai',
      label: i18n.t('iconLabels.cloudDownload')
    }, {
      value: 'icon-shidi-xiaoxi',
      label: i18n.t('iconLabels.message')
    }, {
      value: 'icon-shidi-dingwei',
      label: i18n.t('iconLabels.location')
    }, {
      value: 'icon-shidi-guankan',
      label: i18n.t('iconLabels.view')
    }, {
      value: 'icon-shidi-jinzhiguankan',
      label: i18n.t('iconLabels.noViewing')
    }, {
      value: 'icon-shidi-yirenzheng',
      label: i18n.t('iconLabels.verified')
    }, {
      value: 'icon-shidi-weirenzheng',
      label: i18n.t('iconLabels.unverified')
    }, {
      value: 'icon-shidi-biaoqian',
      label: i18n.t('iconLabels.tag')
    }, {
      value: 'icon-shidi-yonghu',
      label: i18n.t('iconLabels.user')
    }, {
      value: 'icon-shidi-tianjiayonghu',
      label: i18n.t('iconLabels.addUser')
    }, {
      value: 'icon-shidi-shanchuyonghu',
      label: i18n.t('iconLabels.deleteUser')
    }, {
      value: 'icon-shidi-qiehuanyonghu',
      label: i18n.t('iconLabels.switchUser')
    }, {
      value: 'icon-shidi-weixiu',
      label: i18n.t('iconLabels.maintenance')
    }, {
      value: 'icon-shidi-wuliji',
      label: i18n.t('iconLabels.physicalMachine')
    }, {
      value: 'icon-shidi-xuniji',
      label: i18n.t('iconLabels.virtualMachine')
    }, {
      value: 'icon-shidi-docker',
      label: 'docker'
    }, {
      value: 'icon-shidi-luyouqi',
      label: i18n.t('iconLabels.router')
    }, {
      value: 'icon-shidi-jiaohuanji',
      label: i18n.t('iconLabels.switch')
    }, {
      value: 'icon-shidi-fanghuoqiang',
      label: i18n.t('iconLabels.firewall')
    }, {
      value: 'icon-shidi-fuzaijunheng',
      label: i18n.t('iconLabels.loadBalancer')
    }, {
      value: 'icon-shidi-wangka',
      label: i18n.t('iconLabels.nic')
    }, {
      value: 'icon-shidi-neicun',
      label: i18n.t('iconLabels.memory')
    }, {
      value: 'icon-shidi-yingpan',
      label: i18n.t('iconLabels.hardDisk')
    }, {
      value: 'icon-shidi-bumen',
      label: i18n.t('iconLabels.department')
    }, {
      value: 'icon-shidi-chanpin',
      label: i18n.t('iconLabels.product')
    }, {
      value: 'icon-shidi-dayinji',
      label: i18n.t('iconLabels.printer')
    }, {
      value: 'icon-shidi-chajian',
      label: i18n.t('iconLabels.plugin')
    }, {
      value: 'icon-shidi-yingyong',
      label: i18n.t('iconLabels.application')
    }, {
      value: 'icon-shidi-nginx',
      label: 'Nginx'
    }, {
      value: 'icon-shidi-apache',
      label: 'Apache'
    }, {
      value: 'icon-shidi-tomcat',
      label: 'Tomcat'
    }, {
      value: 'icon-shidi-aliyun',
      label: i18n.t('iconLabels.alibabaCloud')
    }, {
      value: 'icon-shidi-tengxunyun',
      label: i18n.t('iconLabels.tencentCloud')
    }, {
      value: 'icon-shidi-huaweiyun',
      label: i18n.t('iconLabels.huaweiCloud')
    }, {
      value: 'icon-shidi-aws',
      label: 'AWS'
    }]
  }, {
    value: 'data',
    label: 'components.data',
    list: [{
      value: 'icon-shidi-bingzhuangtu',
      label: i18n.t('iconLabels.pieChart')
    }, {
      value: 'icon-shidi-huanxingtu',
      label: i18n.t('iconLabels.ringChart')
    }, {
      value: 'icon-shidi-zhuzhuangtu',
      label: i18n.t('iconLabels.barChart')
    }, {
      value: 'icon-shidi-tiaoxingtu',
      label: i18n.t('iconLabels.horizontalBar')
    }, {
      value: 'icon-shidi-mianjitu',
      label: i18n.t('iconLabels.areaChart')
    }, {
      value: 'icon-shidi-pubutu',
      label: i18n.t('iconLabels.waterfallChart')
    }, {
      value: 'icon-shidi-xiangxingtu',
      label: i18n.t('iconLabels.boxPlot')
    }, {
      value: 'icon-shidi-zhexiantu',
      label: i18n.t('iconLabels.lineChart')
    }, {
      value: 'icon-shidi-dianzhuangtu',
      label: i18n.t('iconLabels.scatterPlot')
    }, {
      value: 'icon-shidi-redutu',
      label: i18n.t('iconLabels.heatMap')
    }, {
      value: 'icon-shidi-shangsheng',
      label: i18n.t('iconLabels.rising')
    }, {
      value: 'icon-shidi-xiajiang',
      label: i18n.t('iconLabels.falling')
    }, {
      value: 'icon-shidi-gupiaotu',
      label: i18n.t('iconLabels.stockChart')
    }, {
      value: 'icon-shidi-jijintu',
      label: i18n.t('iconLabels.fundChart')
    }, {
      value: 'icon-shidi-huakuaitu',
      label: i18n.t('iconLabels.sliderChart')
    }, {
      value: 'icon-shidi-leidatu',
      label: i18n.t('iconLabels.radarChart')
    }, {
      value: 'icon-shidi-shishu',
      label: i18n.t('iconLabels.integer')
    }, {
      value: 'icon-shidi-fudianshu',
      label: i18n.t('iconLabels.float')
    }, {
      value: 'icon-shidi-wenben',
      label: i18n.t('iconLabels.text')
    }, {
      value: 'icon-shidi-datetime',
      label: 'datetime'
    }, {
      value: 'icon-shidi-date',
      label: 'date'
    }, {
      value: 'icon-shidi-time',
      label: 'time'
    }, {
      value: 'icon-shidi-json',
      label: 'json'
    }]
  }
]

export const multicolorIconList = [
  {
    value: 'database',
    label: 'components.database',
    list: [{
      value: 'caise-TIDB',
      label: 'TIDB'
    }, {
      value: 'caise-dameng',
      label: i18n.t('iconLabels.dameng')
    }, {
      value: 'caise-kingbase',
      label: 'KingBase'
    }, {
      value: 'caise-TDSQL',
      label: 'TDSQL'
    }, {
      value: 'caise-DB2',
      label: 'DB2'
    }, {
      value: 'caise-oracle',
      label: 'Oracle'
    }, {
      value: 'caise-informix',
      label: 'Informix'
    }, {
      value: 'caise-Sybase',
      label: 'Sybase'
    }, {
      value: 'caise-SQLServer',
      label: 'SQLServer'
    }, {
      value: 'caise-PostgreSQL',
      label: 'PostgreSQL'
    }, {
      value: 'caise-mySQL',
      label: 'mySQL'
    }, {
      value: 'caise-access',
      label: 'access'
    }, {
      value: 'caise-mongodb',
      label: 'mongodb'
    }, {
      value: 'caise-redis',
      label: 'redis'
    }]
  }, {
    value: 'cloud',
    label: 'components.cloud',
    list: [{
      value: 'AWS',
      label: 'AWS'
    }, {
      value: 'Azure',
      label: 'Azure'
    }, {
      value: 'Google_Cloud_Platform',
      label: 'Google Cloud Platform'
    }, {
      value: 'Alibaba_Cloud',
      label: i18n.t('iconLabels.alibabaCloud')
    }, {
      value: 'Huawei_Cloud',
      label: i18n.t('iconLabels.huaweiCloud')
    }, {
      value: 'Tencent_Cloud',
      label: i18n.t('iconLabels.tencentCloud')
    }, {
      value: 'UCloud',
      label: 'UCloud'
    }, {
      value: 'Ctyun',
      label: i18n.t('iconLabels.ctyun')
    }, {
      value: 'ECloud',
      label: i18n.t('iconLabels.ecloud')
    }, {
      value: 'JDCloud',
      label: i18n.t('iconLabels.jdCloud')
    }, {
      value: 'Bytecloud',
      label: i18n.t('iconLabels.byteCloud')
    }, {
      value: 'OpenStack',
      label: 'OpenStack'
    }, {
      value: 'ZStack',
      label: 'ZStack'
    }, {
      value: 'Nutanix',
      label: 'Nutanix'
    }]
  }, {
    value: 'system',
    label: 'components.system',
    list: [{
      value: 'ciase-aix',
      label: 'aix'
    }, {
      value: 'caise-Windows',
      label: 'Windows'
    }, {
      value: 'caise-Linux',
      label: 'Linux'
    }, {
      value: 'caise-unix',
      label: 'Unix'
    }, {
      value: 'caise-Mac',
      label: 'Mac'
    }, {
      value: 'caise-Ubuntu',
      label: 'Ubuntu'
    }, {
      value: 'caise-centos',
      label: 'Centos'
    }, {
      value: 'caise-redhat',
      label: 'Redhat'
    }]
  }, {
    value: 'language',
    label: 'components.language',
    list: [{
      value: 'caise-python',
      label: 'python'
    }, {
      value: 'caise-Java',
      label: 'Java'
    }, {
      value: 'caise-c1',
      label: 'C++'
    }, {
      value: 'caise-c2',
      label: 'C#'
    }, {
      value: 'caise-swift',
      label: 'Swift'
    }, {
      value: 'caise-php',
      label: 'PHP'
    }, {
      value: 'caise-shell',
      label: 'Shell'
    }, {
      value: 'caise-powershell',
      label: 'PowerShell'
    }, {
      value: 'caise-bat',
      label: 'Bat'
    }]
  }, {
    value: 'status',
    label: 'components.status',
    list: [{
      value: 'caise-yiwen',
      label: i18n.t('iconLabels.question')
    }, {
      value: 'caise-zanting',
      label: i18n.t('iconLabels.pause')
    }, {
      value: 'caise-tianjia',
      label: i18n.t('iconLabels.add')
    }, {
      value: 'caise-jianqu',
      label: i18n.t('iconLabels.subtract')
    }, {
      value: 'caise-quxiao',
      label: i18n.t('iconLabels.cancel')
    }, {
      value: 'caise-queren',
      label: i18n.t('iconLabels.confirm')
    }, {
      value: 'caise-jinggao',
      label: i18n.t('iconLabels.warning')
    }, {
      value: 'caise-jinzhi',
      label: i18n.t('iconLabels.forbidden')
    }, {
      value: 'caise-shuoming',
      label: i18n.t('iconLabels.description')
    }, {
      value: 'caise-chulizhong',
      label: i18n.t('iconLabels.processing')
    }, {
      value: 'caise-zaixian',
      label: i18n.t('iconLabels.online')
    }, {
      value: 'caise-xiaxian',
      label: i18n.t('iconLabels.offline')
    }]
  }, {
    value: 'caise-application',
    label: 'components.commonComponent',
    list: [{
      value: 'caise-websphere',
      label: 'WebSphere'
    }, {
      value: 'caise-vps',
      label: 'VPS'
    }, {
      value: 'caise-F5',
      label: 'F5'
    }, {
      value: 'caise-HAProxy',
      label: 'HAProxy'
    }, {
      value: 'caise-kafka',
      label: 'kafka'
    }, {
      value: 'caise-dongfangtong',
      label: i18n.t('iconLabels.tongtech')
    }, {
      value: 'cmdb-vcenter',
      label: 'VCenter'
    }, {
      value: 'ops-KVM',
      label: 'KVM'
    }, {
      value: 'caise-JBoss',
      label: 'JBoss'
    }, {
      value: 'caise-weblogic',
      label: 'WebLogic'
    }, {
      value: 'caise-disk_array',
      label: i18n.t('iconLabels.diskArray')
    }, {
      value: 'caise-fiber',
      label: i18n.t('iconLabels.fiberSwitch')
    }, {
      value: 'caise-bandwidth_line',
      label: i18n.t('iconLabels.bandwidthLine')
    }, {
      value: 'caise-pc',
      label: 'PC'
    }, {
      value: 'caise-rack',
      label: i18n.t('iconLabels.rack')
    }, {
      value: 'caise-computer_room',
      label: i18n.t('iconLabels.computerRoom')
    }, {
      value: 'caise-ip_address',
      label: i18n.t('iconLabels.ipAddress')
    }, {
      value: 'caise_pool',
      label: i18n.t('iconLabels.ipPool')
    }, {
      value: 'caise-storage_volume1',
      label: i18n.t('iconLabels.storageVolume')
    }, {
      value: 'caise-virtualization',
      label: i18n.t('iconLabels.virtualization')
    }, {
      value: 'caise-business',
      label: i18n.t('iconLabels.business')
    }, {
      value: 'caise-database',
      label: i18n.t('iconLabels.database')
    }, {
      value: 'caise-middleware',
      label: i18n.t('iconLabels.middleware')
    }, {
      value: 'caise-websever',
      label: 'websever'
    }, {
      value: 'caise-message_queue',
      label: i18n.t('iconLabels.messageQueue')
    }, {
      value: 'caise-load_balancing',
      label: i18n.t('iconLabels.loadBalancer')
    }, {
      value: 'caise-storage_device',
      label: i18n.t('iconLabels.storageDevice')
    }, {
      value: 'caise-network_devices',
      label: i18n.t('iconLabels.networkDevice')
    }, {
      value: 'caise-computer',
      label: i18n.t('iconLabels.computer')
    }, {
      value: 'caise-hardware',
      label: i18n.t('iconLabels.hardware')
    }, {
      value: 'caise-data_center2',
      label: i18n.t('iconLabels.dataCenter')
    }, {
      value: 'caise-hyperV',
      label: 'hyperV'
    }, {
      value: 'caise-IPAM',
      label: 'IPAM'
    }, {
      value: 'caise-system',
      label: i18n.t('iconLabels.operatingSystem')
    }, {
      value: 'caise-public_cloud',
      label: i18n.t('iconLabels.publicCloud')
    }, {
      value: 'caise-data_center',
      label: i18n.t('iconLabels.dataCenter')
    }, {
      value: 'caise-folder',
      label: i18n.t('iconLabels.folder')
    }, {
      value: 'caise-resource_pool',
      label: i18n.t('iconLabels.resourcePool')
    }, {
      value: 'caise-network',
      label: i18n.t('iconLabels.network')
    }, {
      value: 'caise-distributed_switch',
      label: i18n.t('iconLabels.distributedSwitch')
    }, {
      value: 'caise-standard_switch',
      label: i18n.t('iconLabels.standardSwitch')
    }, {
      value: 'caise-host_cluster',
      label: i18n.t('iconLabels.hostCluster')
    }, {
      value: 'caise-storage_cluster',
      label: i18n.t('iconLabels.dataStorageCluster')
    }, {
      value: 'caise-data_storage',
      label: i18n.t('iconLabels.dataStorage')
    }, {
      value: 'caise-yilianjie',
      label: i18n.t('iconLabels.connected')
    }, {
      value: 'caise-weilianjie',
      label: i18n.t('iconLabels.disconnected')
    }, {
      value: 'caise-shoucang',
      label: i18n.t('iconLabels.favorites')
    }, {
      value: 'caise-baojing',
      label: i18n.t('iconLabels.alarm')
    }, {
      value: 'caise-erweima',
      label: i18n.t('iconLabels.qrCode')
    }, {
      value: 'caise-fenzhi',
      label: i18n.t('iconLabels.branch')
    }, {
      value: 'caise-yunshuju',
      label: i18n.t('iconLabels.cloudData')
    }, {
      value: 'caise-yunshangchuan',
      label: i18n.t('iconLabels.cloudUpload')
    }, {
      value: 'caise-yunxiazai',
      label: i18n.t('iconLabels.cloudDownload')
    }, {
      value: 'caise-xiaoxi',
      label: i18n.t('iconLabels.message')
    }, {
      value: 'caise-dingwei',
      label: i18n.t('iconLabels.location')
    }, {
      value: 'caise-guankan',
      label: i18n.t('iconLabels.view')
    }, {
      value: 'caise-jinzhiguankan',
      label: i18n.t('iconLabels.noViewing')
    }, {
      value: 'caise-yirenzheng',
      label: i18n.t('iconLabels.verified')
    }, {
      value: 'caise-weirenzheng',
      label: i18n.t('iconLabels.unverified')
    }, {
      value: 'caise-biaoqian',
      label: i18n.t('iconLabels.tag')
    }, {
      value: 'caise-yonghu',
      label: i18n.t('iconLabels.user')
    }, {
      value: 'caise-tianjiayonghu',
      label: i18n.t('iconLabels.addUser')
    }, {
      value: 'caise-shanchuyonghu',
      label: i18n.t('iconLabels.deleteUser')
    }, {
      value: 'caise-qiehuanyonghu',
      label: i18n.t('iconLabels.switchUser')
    }, {
      value: 'caise-weixiu',
      label: i18n.t('iconLabels.maintenance')
    }, {
      value: 'caise-wuliji',
      label: i18n.t('iconLabels.physicalMachine')
    }, {
      value: 'caise-xuniji',
      label: i18n.t('iconLabels.virtualMachine')
    }, {
      value: 'caise-docker',
      label: 'docker'
    }, {
      value: 'caise-luyouqi',
      label: i18n.t('iconLabels.router')
    }, {
      value: 'caise-jiaohuanji',
      label: i18n.t('iconLabels.switch')
    }, {
      value: 'caise-fanghuoqiang',
      label: i18n.t('iconLabels.firewall')
    }, {
      value: 'caise-fuzaijunheng',
      label: i18n.t('iconLabels.loadBalancer')
    }, {
      value: 'caise-wangka',
      label: i18n.t('iconLabels.nic')
    }, {
      value: 'caise-neicun',
      label: i18n.t('iconLabels.memory')
    }, {
      value: 'caise-yingpan',
      label: i18n.t('iconLabels.hardDisk')
    }, {
      value: 'caise-bumen',
      label: i18n.t('iconLabels.department')
    }, {
      value: 'caise-chanpin',
      label: i18n.t('iconLabels.product')
    }, {
      value: 'caise-yingyong',
      label: i18n.t('iconLabels.application')
    }, {
      value: 'caise-dayinji',
      label: i18n.t('iconLabels.printer')
    }, {
      value: 'caise-chajian',
      label: i18n.t('iconLabels.plugin')
    }, {
      value: 'caise-nginx',
      label: 'Nginx'
    }, {
      value: 'caise-apache',
      label: 'Apache'
    }, {
      value: 'caise-tomcat',
      label: 'Tomcat'
    }, {
      value: 'caise-VPC',
      label: 'VPC'
    }, {
      value: 'caise-CDN',
      label: 'CDN'
    }, {
      value: 'caise-OOS',
      label: i18n.t('iconLabels.objectStorage')
    }]
  }, {
    value: 'data',
    label: 'components.data',
    list: [{
      value: 'caise-bingzhuangtu',
      label: i18n.t('iconLabels.pieChart')
    }, {
      value: 'caise-huanxingtu',
      label: i18n.t('iconLabels.ringChart')
    }, {
      value: 'caise-zhuzhuangtu',
      label: i18n.t('iconLabels.barChart')
    }, {
      value: 'caise-tiaoxingtu',
      label: i18n.t('iconLabels.horizontalBar')
    }, {
      value: 'caise-mianjitu',
      label: i18n.t('iconLabels.areaChart')
    }, {
      value: 'caise-pubutu',
      label: i18n.t('iconLabels.waterfallChart')
    }, {
      value: 'caise-xiangxingtu',
      label: i18n.t('iconLabels.boxPlot')
    }, {
      value: 'caise-zhexiantu',
      label: i18n.t('iconLabels.lineChart')
    }, {
      value: 'caise-dianzhuangtu',
      label: i18n.t('iconLabels.scatterPlot')
    }, {
      value: 'caise-redutu',
      label: i18n.t('iconLabels.heatMap')
    }, {
      value: 'caise-shangsheng',
      label: i18n.t('iconLabels.rising')
    }, {
      value: 'caise-xiajiang',
      label: i18n.t('iconLabels.falling')
    }, {
      value: 'caise-gupiaotu',
      label: i18n.t('iconLabels.stockChart')
    }, {
      value: 'caise-jijintu',
      label: i18n.t('iconLabels.fundChart')
    }, {
      value: 'caise-huakuaitu',
      label: i18n.t('iconLabels.sliderChart')
    }, {
      value: 'caise-leidatu',
      label: i18n.t('iconLabels.radarChart')
    }, {
      value: 'caise-shishu',
      label: i18n.t('iconLabels.integer')
    }, {
      value: 'caise-fudianshu',
      label: i18n.t('iconLabels.float')
    }, {
      value: 'caise-wenben',
      label: i18n.t('iconLabels.text')
    }, {
      value: 'caise-datetime',
      label: 'datetime'
    }, {
      value: 'caise-date',
      label: 'date'
    }, {
      value: 'caise-time',
      label: 'time'
    }, {
      value: 'caise-json',
      label: 'json'
    }]
  }
]
